240219.111228.HKT revise misc_app

diff --git a/misc_app b/misc_app
--- a/misc_app
+++ b/misc_app
@@ -20,7 +20,8 @@ elif [[ "$RUNNER_OS" == "macOS" ]] ; then
     make --version
     cmake --version
     ninja --version
-    (brew install gdb &> /dev/null && gbd --version) || echo "!!! gdb cannot be installed !!!"  # gdb cannot be installed by brew on macOS 14 with Apple Silicon chips as of 20240219
+    # gdb cannot be installed by brew on macOS 14 with Apple Silicon chips as of 20240219
+    (brew install gdb &> /dev/null && gbd --version) || echo "!!! WARNING: gdb cannot be installed !!!"
 elif [[ "$RUNNER_OS" == "Windows" ]] ; then
     choco install wget make cmake ninja --no-progress  # gdb cannot be installed by choco
     make --version
